/**
 * Dump every prompt the TypeScript pipeline uses into one markdown file.
 *
 * The prompts live in four places and are assembled at request time, so no
 * single file shows what the model actually receives. This walks the sources,
 * pulls each block out, and writes them in the order they reach the model.
 *
 *   npx tsx scripts/dump-prompts.ts [outfile]
 */
import fs from "fs";
import path from "path";

const ROOT = process.cwd();
const OUT = process.argv[2] || path.join(ROOT, "PROMPTS.md");

const read = (p: string) => {
  try { return fs.readFileSync(path.join(ROOT, p), "utf-8"); } catch { return ""; }
};
const kb = (s: string) => `${Math.round(s.length / 1024)} KB`;

/** Every `prompt += \`...\`` literal in a file, in source order. */
function directives(src: string): string[] {
  return [...src.matchAll(/prompt \+= `([\s\S]*?)`;/g)]
    .map((m) => m[1].replace(/\\n/g, "\n").trim())
    .filter((d) => d.length > 20);
}

/** A named const holding a template/string literal or an object literal. */
function block(src: string, name: string): string {
  // \r? matters: assets-gen.ts is CRLF while gemini.ts and image-prompt.ts are
  // LF, so a terminator written as ;\n\n matched three blocks and silently
  // returned empty for the three in the CRLF file.
  const re = new RegExp(`(?:const|export const) ${name}[^=]*=\\s*([\\s\\S]*?);\\r?\\n\\r?\\n`, "m");
  return src.match(re)?.[1]?.trim() ?? "";
}

const gemini = read("src/lib/gemini.ts");
const assets = read("src/lib/assets-gen.ts");
const resume = read("src/lib/resume.ts");
const kit = read("src/lib/profile-kit.ts");
const imgp = read("src/lib/image-prompt.ts");

const KNOWLEDGE = [
  "src/lib/prompts/linkedin-system-prompt.md",
  "src/lib/knowledge/career-os-content-brain.md",
  "src/lib/knowledge/viral-post-patterns.md",
  "src/lib/knowledge/creator-evidence.md",
  "src/lib/knowledge/top-posts-examples.md",
  "src/lib/knowledge/carousel-master.md",
  "src/lib/knowledge/carousel-design-patterns.md",
  "src/lib/knowledge/koyopo-slide-rules.md",
  "src/lib/knowledge/winning-carousel-playbook.md",
];

const out: string[] = [];
const h = (n: number, t: string) => out.push(`\n${"#".repeat(n)} ${t}\n`);
const fence = (s: string, lang = "text") => out.push("```" + lang + "\n" + s + "\n```");

out.push("# Every prompt in the pipeline\n");
out.push("Generated by `scripts/dump-prompts.ts`. Read top to bottom: this is the");
out.push("order in which the model receives things.\n");

// ── 1 ───────────────────────────────────────────────────────────────────────
h(2, "1. Resume analysis — src/lib/resume.ts");
out.push("Runs once per uploaded CV. Its output becomes `profileContext`, which is");
out.push("prepended to every generation afterwards.\n");
const rp = resume.match(/`([\s\S]*?"aestheticStyle"[\s\S]*?)`/)?.[1];
fence(rp ? rp.trim() : "(extraction prompt not matched — see src/lib/resume.ts)");

// ── 2 ───────────────────────────────────────────────────────────────────────
h(2, "2. System prompt — assembled at module load");
out.push("`gemini.ts` concatenates these into one system instruction, in this order:\n");
for (const k of KNOWLEDGE.slice(0, 5)) out.push(`- \`${k}\` — ${kb(read(k))}`);
out.push(`\nTotal system instruction: **${kb(KNOWLEDGE.slice(0, 5).map(read).join(""))}**`);
out.push("\nCarousels additionally receive:\n");
for (const k of KNOWLEDGE.slice(5)) out.push(`- \`${k}\` — ${kb(read(k))}`);

// ── 3 ───────────────────────────────────────────────────────────────────────
h(2, "3. Per-request directives — src/lib/gemini.ts");
out.push("Appended to the user turn, in source order. This is where the actual");
out.push("instructions live.\n");
directives(gemini).forEach((d, i) => {
  h(3, `3.${i + 1}`);
  fence(d, "markdown");
});

h(3, "Assignment tables");
out.push("Rotated per post so a batch does not come back as three of the same thing.\n");
for (const n of ["HOOK_ARCHETYPES", "SKELETONS", "CAROUSEL_TYPES"]) {
  const b = block(gemini, n);
  if (b) { out.push(`\n**${n}**`); fence(b, "ts"); }
}

h(3, "TONE_DIRECTIVES");
fence(block(gemini, "TONE_DIRECTIVES") || "(not matched)", "ts");

h(3, "DECK_STYLE_DIRECTIVES");
fence(block(gemini, "DECK_STYLE_DIRECTIVES") || "(not matched)", "ts");

h(3, "Refinement pass");
out.push("Carousels get a second call, graded against the scorecard.\n");
const refine = gemini.match(/const system = `([\s\S]*?)`;/)?.[1];
fence(refine ? refine.replace(/\\n/g, "\n").trim() : "(not matched)", "markdown");

// ── 4 ───────────────────────────────────────────────────────────────────────
h(2, "4. Assets — src/lib/assets-gen.ts");
out.push("Six independent prompts, one per tab, each prefixed with a shared VOICE.\n");
h(3, "VOICE (prefixed to all six)");
fence(block(assets, "VOICE") || "(not matched)", "ts");
h(3, "PROMPTS");
fence(block(assets, "PROMPTS") || "(not matched)", "ts");
h(3, "ANGLES — rotated per press of Generate");
fence(block(assets, "ANGLES") || "(not matched)", "ts");

// ── 5 ───────────────────────────────────────────────────────────────────────
h(2, "5. Profile Kit — src/lib/profile-kit.ts");
const kp = kit.match(/`([\s\S]*?"alignment"[\s\S]*?)`/)?.[1];
fence(kp ? kp.trim() : "(not matched — see src/lib/profile-kit.ts)");

// ── 6 ───────────────────────────────────────────────────────────────────────
h(2, "6. Image prompts — src/lib/image-prompt.ts");
out.push("Every style composes its scene fragment with these two constants.\n");
for (const n of ["NO_TEXT", "QUALITY"]) {
  const b = block(imgp, n);
  if (b) { out.push(`\n**${n}**`); fence(b, "ts"); }
}
h(3, "AESTHETICS — the 29 design movements");
fence(block(imgp, "AESTHETICS") || "(not matched)", "ts");

fs.writeFileSync(OUT, out.join("\n"), "utf-8");
console.log(`  wrote ${OUT}`);
console.log(`  ${(fs.statSync(OUT).size / 1024).toFixed(0)} KB, ${out.join("\n").split("\n").length} lines`);
