/**
 * Generates src/lib/font-data.ts — base64-embedded Poppins faces.
 *
 * Serverless runtimes (Vercel / AWS Lambda) ship with NO installed fonts, so
 * librsvg silently drops SVG <text> and slides come out as bare backgrounds
 * ("no caption"). Embedding the bundled TTFs as @font-face data URIs makes the
 * text render identically on every machine. Run: npx tsx scripts/gen-fonts.ts
 */
import fs from "fs";
import path from "path";

const SRC = path.join(process.cwd(), "assets", "fonts");
const OUT = path.join(process.cwd(), "src", "lib", "font-data.ts");

// weight, style, filename  — order matters only for readability.
const FACES = [
  { weight: "400", style: "normal", file: "Poppins-Regular.ttf", var: "REG" },
  { weight: "600", style: "normal", file: "Poppins-SemiBold.ttf", var: "SEMIBOLD" },
  { weight: "700", style: "normal", file: "Poppins-Bold.ttf", var: "BOLD" },
  { weight: "800", style: "normal", file: "Poppins-ExtraBold.ttf", var: "EXTRABOLD" },
  { weight: "900", style: "normal", file: "Poppins-Black.ttf", var: "BLACK" },
  { weight: "400", style: "italic", file: "Poppins-Italic.ttf", var: "ITALIC" },
];

const lines: string[] = [
  "// AUTO-GENERATED by scripts/gen-fonts.ts — do not edit by hand.",
  "// Base64 of the bundled Poppins TTFs so librsvg can render SVG <text> on",
  "// serverless runtimes (Vercel/AWS Lambda) that ship with no installed fonts.",
  'import fs from "fs";',
  'import path from "path";',
  "",
  "const DIR = path.join(process.cwd(), \"assets\", \"fonts\");",
  "",
];

const faceMap: string[] = [];

for (const f of FACES) {
  const buf = fs.readFileSync(path.join(SRC, f.file));
  const b64 = buf.toString("base64");
  lines.push(`export const POPPINS_${f.var} =\n  ${JSON.stringify(b64)};`);
  lines.push("");
  faceMap.push(`  { family: "Poppins", weight: "${f.weight}", style: "${f.style}", var: POPPINS_${f.var} },`);
}

lines.push("/** All faces, as a registry the SVG builders iterate. */");
lines.push("export const POPPINS_FACES = [");
lines.push(...faceMap);
lines.push("];");
lines.push("");
lines.push("/**");
lines.push(" * The <style> block to place at the top of ANY SVG that draws text.",
  " * Registers every face the app uses under one @font-face family so text is",
  " * never affected by which fonts the host machine happens to have.",
  " */");
lines.push("export function poppinsCss(): string {");
lines.push('  return `<style>');
lines.push(`    @font-face{font-family:"Poppins";font-weight:400;font-style:normal;src:url(data:font/ttf;base64,\${POPPINS_REG})}`);
lines.push(`    @font-face{font-family:"Poppins";font-weight:600;font-style:normal;src:url(data:font/ttf;base64,\${POPPINS_SEMIBOLD})}`);
lines.push(`    @font-face{font-family:"Poppins";font-weight:700;font-style:normal;src:url(data:font/ttf;base64,\${POPPINS_BOLD})}`);
lines.push(`    @font-face{font-family:"Poppins";font-weight:800;font-style:normal;src:url(data:font/ttf;base64,\${POPPINS_EXTRABOLD})}`);
lines.push(`    @font-face{font-family:"Poppins";font-weight:900;font-style:normal;src:url(data:font/ttf;base64,\${POPPINS_BLACK})}`);
lines.push(`    @font-face{font-family:"Poppins";font-weight:400;font-style:italic;src:url(data:font/ttf;base64,\${POPPINS_ITALIC})}`);
lines.push("  </style>`;");
lines.push("}");
lines.push("");

fs.writeFileSync(OUT, lines.join("\n"));
console.log("wrote", OUT, "(bytes:", fs.statSync(OUT).size + ")");